// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxuqAVuogslNYi_DvrTQvvLf_lfSymsw8',
    appId: '1:803588697996:web:04128df22d6878bced70a9',
    messagingSenderId: '803588697996',
    projectId: 'new-portfolio-ehi-j',
    authDomain: 'new-portfolio-ehi-j.firebaseapp.com',
    storageBucket: 'new-portfolio-ehi-j.appspot.com',
    measurementId: 'G-57L3ZEZ5EY',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvqDS03_UJ_JL9gp8wwE7bLtv64Do2Q_8',
    appId: '1:803588697996:web:f8153262d7159418ed70a9',
    messagingSenderId: '803588697996',
    projectId: 'new-portfolio-ehi-j',
    authDomain: 'new-portfolio-ehi-j.firebaseapp.com',
    storageBucket: 'new-portfolio-ehi-j.appspot.com',
    measurementId: 'G-PPRN99W1P1',
  );
}
